In [1]:
import torch
from torch.utils.data import Dataset, DataLoader
from sklearn.datasets import make_classification

### Generate Demo Data

In [2]:
# create a synthetic classification dataset
X_train, y_train = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

X_train shape: (10, 2)
y_train shape: (10,)


In [3]:
X_train

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [4]:
y_train

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

### Dataset and DaLoader

In [5]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [6]:
class MyDataset(Dataset):
    def __init__(self, features, labels):
        # for small dataset copy whole dataset to gpu
        self.features = torch.tensor(features, dtype=torch.float32, device=device)
        self.labels = torch.tensor(labels, dtype=torch.long, device=device)

    def __getitem__(self, index):
        x = self.features[index]
        y = self.labels[index]        
        return x, y

    def __len__(self):
        return self.labels.shape[0]

train_ds = MyDataset(X_train, y_train)
train_loader = DataLoader(dataset=train_ds, batch_size=2, shuffle=True)

In [7]:
len(train_ds)

10

In [8]:
train_ds[2]

(tensor([-2.8954,  1.9769], device='cuda:0'), tensor(0, device='cuda:0'))

In [9]:
len(train_loader)

5

In [10]:
for x_batch, y_batch in train_loader:
    # for big dataset copy batch only to gpu
    #x_batch = x_batch.to(device)
    #y_batch = y_batch.to(device)
    
    print(x_batch)
    print(y_batch)
    print("-"*40)

tensor([[-0.5872, -1.9717],
        [ 1.8997,  0.8344]], device='cuda:0')
tensor([0, 1], device='cuda:0')
----------------------------------------
tensor([[-0.7206, -0.9606],
        [-1.1402, -0.8388]], device='cuda:0')
tensor([0, 0], device='cuda:0')
----------------------------------------
tensor([[ 1.7774,  1.5116],
        [-2.8954,  1.9769]], device='cuda:0')
tensor([1, 0], device='cuda:0')
----------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.0683, -0.9701]], device='cuda:0')
tensor([1, 1], device='cuda:0')
----------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]], device='cuda:0')
tensor([0, 1], device='cuda:0')
----------------------------------------
